services:
  postfix:
    image: registry.ddos-guard.net/postfix:3.9.0
    container_name: postfix
    restart: unless-stopped
    volumes:
      - /storage/postfix-mail-sender/mail-templates:/root/mail-templates
    ports:
    #  for web-dev:
    #  - 25:25
      - 2525:25
  alias:
    image: registry.ddos-guard.net/alpine:3.18
    volumes:
      - /usr/local/bin:/usr/local/bin
    depends_on:
      - postfix
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        if [ ! -f /usr/local/bin/sendmail ]; then
          touch /usr/local/bin/sendmail
          echo 'sudo cp "$2" /storage/postfix-mail-sender/mail-templates/' >> /usr/local/bin/sendmail
          echo 'sudo docker exec postfix sh -c "sendmail -f $1 -t < ~/mail-templates/$(basename $2)"' >> /usr/local/bin/sendmail
          echo 'sudo rm /storage/postfix-mail-sender/mail-templates/$(basename $2)' >> /usr/local/bin/sendmail
          chmod +x /usr/local/bin/sendmail
        else
          echo "sendmail already exists, skipping script creation."
        fi
